### ISSUE TITLE
please add mouse move cross line feature

### ISSUE THREAD

**Issue by adamshe** [chartjs/chartjs-chart-financial#15]
hi, if you can introduce a cross line to get tooltip on a fix area for data of o,c,h,l,v, it will be great
A reference is this:
https://bitcoinwisdom.com/markets/bitstamp/btcusd

Thanks.

**Comment by benmccann** [comment]
Thanks. That could be a good idea. I'm trying to fix the date formatting on the tooltip first https://github.com/chartjs/Chart.js/pull/4583, but this could be interesting to support

**Comment by benmccann** [comment]
After thinking about this for a little while I've realized that the best way to implement this would be as a generic chart.js plugin that can work on any chart

Since we shouldn't include it in this repo, I'm going to close this issue. I think the feature is a great one though. I'd love it if you implemented the plugin!

**Comment by benmccann** [comment]
Actually I think https://github.com/chartjs/chartjs-plugin-annotation might do what you want
