### ISSUE TITLE
Improved samples

### ISSUE THREAD

**Issue by mce1978** [chartjs/chartjs-chart-financial#5]
I just want to try this out. Could you please provide a sample that works out of the box in the samples folder?

I am looking at index.html. Chart.bundle.js could perhaps be a cdn reference? Chart.Financial.js could be prebuilt and available?

Well done!

**Comment by benmccann** [comment]
Yes, it will be nice to publish some samples (possibly on GitHub pages) that you can see without checking out the repo

It's useful during development to have samples that point to the local version, so I don't want the version in the samples directory to lose that functionality

**Comment by tapir** [comment]
Also sample is now effectively not functional since there is no documentation how to build Chart.Financial.js

**Comment by mce1978** [comment]
Would it be too much work to add a sample that uses the latest working chart.financial.js ?

I really want to try this but I am not using your build environment.

**Comment by benmccann** [comment]
I've added instructions for building to the README

**Comment by ShareinSK** [comment]
On which port is the sample running?

**Comment by joepsyko** [comment]
Thanks for adding instructions, I tried the chart, I think I'll use it in my project

**Comment by ShareinSK** [comment]
How do I see the sample app?
And how can i include this in my app?

I am new to this. Pls help

**Comment by joepsyko** [comment]
You should see the "samples" directory which contains the example

**Comment by ShareinSK** [comment]
How can we include this in our app.

**Comment by joepsyko** [comment]
see the example, it's self-explanatory

**Comment by pekkatuovinen** [comment]
"We are aiming to make Chart.js the only popular JavaScript library that is both performant and has good timescale handling." 

a really cute goal to have.

...aaaand then fuck that goal TOTALLY up by only providing a smuck nerd way for using the damn library! SERIOUSLY come on! I need to install WAMP on my PC now to use this single fuc**ng library on my hosting? I can use the chart.js library like it is supposed to work (copy files, use them on HTML) but to get a small add-on for it I would need to have my fuc**ing own server!?!? Why the heck can't you just pre build SOME version of this library that works?? Doesn't even need to be always the latest version! That is, if you really want someone to actually use this? Maaaaaany developers only use some hosted environment which means they can not build shit and many don't even know how but are still able to do things with javascript. People are asking nicely on many threads how to use this code, where to find the files, and you just don't understand what the problem here is, or you do understand their problem but you just don't care. This libarary is not going to get popular if you don't let people have it! Think about it: if jQuery would only have been available through building, it really would still be a small niche library, but because they have it available easily it is really popular.

**Comment by loicbourgois** [comment]
Samples are now available at https://chartjs.github.io/chartjs-chart-financial/
The source is in [master/docs](https://github.com/chartjs/chartjs-chart-financial/tree/master/docs)

**Comment by loicbourgois** [comment]
@benmccann should this issue get closed ?
